---
input_dir: ./data
output_dir: ./results
cl_decay_steps: 2000
filter_type: random_walk
gc_step: 1
horizon: 3
input_dim: 1
l1_decay: 0
lags: 9
log_level: INFO
matrix_type: DCCA
num_rnn_layers: 2
num_rnn_units: 32
output_dim: 1
scaler: Standard
signals:
- mobile
- temperature
- humidity
test_batch_size: 64
train_batch_size: 64
use_curriculum_learning: False
train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 60
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_to_keep: 100
  max_grad_norm: 5
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 20
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 9
